# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

os: osx
osx_image: xcode11.5
language: swift
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
- pod lib lint
- xcodebuild -workspace Example/MeCardParser.xcworkspace -scheme MeCardParser-Example clean
- xcodebuild -workspace Example/MeCardParser.xcworkspace -scheme MeCardParser-Example -sdk iphonesimulator13.5
